#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CouchbaseConnect2014.Android.Resource", IsApplication=true)]

namespace CouchbaseConnect2014.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::CouchbaseConnect2014.Android.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::CouchbaseConnect2014.Android.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::CouchbaseConnect2014.Android.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::CouchbaseConnect2014.Android.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::CouchbaseConnect2014.Android.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::CouchbaseConnect2014.Android.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::CouchbaseConnect2014.Android.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::CouchbaseConnect2014.Android.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::CouchbaseConnect2014.Android.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::CouchbaseConnect2014.Android.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::CouchbaseConnect2014.Android.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::CouchbaseConnect2014.Android.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::CouchbaseConnect2014.Android.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::CouchbaseConnect2014.Android.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::CouchbaseConnect2014.Android.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::CouchbaseConnect2014.Android.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::CouchbaseConnect2014.Android.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::CouchbaseConnect2014.Android.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::CouchbaseConnect2014.Android.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::CouchbaseConnect2014.Android.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::CouchbaseConnect2014.Android.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::CouchbaseConnect2014.Android.Resource.Layout.test_suite;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::CouchbaseConnect2014.Android.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::CouchbaseConnect2014.Android.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::CouchbaseConnect2014.Android.Resource.Layout.zxingscannerfragmentlayout;
			global::Couchbase.Lite.Android.Resource.String.library_name = global::CouchbaseConnect2014.Android.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070003
			public const int camera_switch_visibility_entries = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int camera_switch_visibility_entry_values = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int msi_plessey_checksum_entries = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int msi_plessey_checksum_entry_values = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int custom_theme_color = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int text_theme_color = 2131230721;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_pic = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int camera_large = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int camera_small = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int check_black = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int check_box_off = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int check_box_on = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int comingSoon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int compose = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int fadeout = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int filter = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int filter_0 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int filter_1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int filter_2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int filter_3 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int filter_4 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int filter_5 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int filter_6 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_launcher = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int menu = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int pip = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int pip_selected = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int plus = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int qr = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int radio_off = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int radio_off_black = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int radio_on = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int rateButton = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int splash = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int SplashScreen = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int star_off = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int star_on = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int surveyShirt = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int temp_add_contact = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int temp_circlePic = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int temp_radio_off = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int temp_radio_on = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int temp_slideout = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int temp_twitterIcon = 2130837543;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000d
			public const int OptionHostName = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int OptionPort = 2131361806;
			
			// aapt resource value: 0x7f0a000c
			public const int OptionRemoteServer = 2131361804;
			
			// aapt resource value: 0x7f0a0021
			public const int OptionsButton = 2131361825;
			
			// aapt resource value: 0x7f0a001c
			public const int ResultFullName = 2131361820;
			
			// aapt resource value: 0x7f0a001e
			public const int ResultMessage = 2131361822;
			
			// aapt resource value: 0x7f0a001d
			public const int ResultResultState = 2131361821;
			
			// aapt resource value: 0x7f0a001b
			public const int ResultRunSingleMethodTest = 2131361819;
			
			// aapt resource value: 0x7f0a001f
			public const int ResultStackTrace = 2131361823;
			
			// aapt resource value: 0x7f0a0012
			public const int ResultsFailed = 2131361810;
			
			// aapt resource value: 0x7f0a000f
			public const int ResultsId = 2131361807;
			
			// aapt resource value: 0x7f0a0013
			public const int ResultsIgnored = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int ResultsInconclusive = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int ResultsMessage = 2131361813;
			
			// aapt resource value: 0x7f0a0011
			public const int ResultsPassed = 2131361809;
			
			// aapt resource value: 0x7f0a0010
			public const int ResultsResult = 2131361808;
			
			// aapt resource value: 0x7f0a0020
			public const int RunTestsButton = 2131361824;
			
			// aapt resource value: 0x7f0a0022
			public const int TestSuiteListView = 2131361826;
			
			// aapt resource value: 0x7f0a0006
			public const int choose = 2131361798;
			
			// aapt resource value: 0x7f0a0023
			public const int contentFrame = 2131361827;
			
			// aapt resource value: 0x7f0a0009
			public const int fs_location = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int fs_select = 2131361802;
			
			// aapt resource value: 0x7f0a0007
			public const int fs_title = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int fs_track = 2131361800;
			
			// aapt resource value: 0x7f0a0005
			public const int image = 2131361797;
			
			// aapt resource value: 0x7f0a000b
			public const int label = 2131361803;
			
			// aapt resource value: 0x7f0a0002
			public const int location = 2131361794;
			
			// aapt resource value: 0x7f0a001a
			public const int seekBarPrefBarContainer = 2131361818;
			
			// aapt resource value: 0x7f0a0019
			public const int seekBarPrefUnitsLeft = 2131361817;
			
			// aapt resource value: 0x7f0a0017
			public const int seekBarPrefUnitsRight = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int seekBarPrefValue = 2131361816;
			
			// aapt resource value: 0x7f0a0004
			public const int time = 2131361796;
			
			// aapt resource value: 0x7f0a0003
			public const int timelabel = 2131361795;
			
			// aapt resource value: 0x7f0a0000
			public const int title = 2131361792;
			
			// aapt resource value: 0x7f0a0016
			public const int titleLayout = 2131361814;
			
			// aapt resource value: 0x7f0a0001
			public const int track = 2131361793;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AgendaCell = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FullScheduleCell = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int options = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int results = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ScavengerHuntCell = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int seek_bar_preference = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int test_result = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int test_suite = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int zxingscanneractivitylayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscannerfragmentlayout = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int beep = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int camera_swap_icon = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int camera_swap_icon_pressed = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int flashlight_turn_off_icon = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int flashlight_turn_off_icon_pressed = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int flashlight_turn_on_icon = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int flashlight_turn_on_icon_pressed = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int ic_btn_search = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int poweredby2x = 2131034120;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000a
			public const int app_name = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int hello = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int scanditsdk_barcode_decoding_in_progress = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int scanditsdk_barcode_presence_detected = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int scanditsdk_initial_scan_screen_state = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int scanditsdk_left_button_caption = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int scanditsdk_left_button_caption_when_keypad_visible = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int scanditsdk_right_button_caption = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int scanditsdk_right_button_caption_when_keypad_visible = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int scanditsdk_searchbar_placeholder = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int scanditsdk_title_message = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int version = 2131099659;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int CustomTheme = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int Theme_Splash = 2131296257;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
