#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamarinScanditSDKDemoAndroid.Resource", IsApplication=true)]

namespace XamarinScanditSDKDemoAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060003
			public const int camera_switch_visibility_entries = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int camera_switch_visibility_entry_values = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int msi_plessey_checksum_entries = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int msi_plessey_checksum_entry_values = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int myButton = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int seekBarPrefBarContainer = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int seekBarPrefUnitsLeft = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int seekBarPrefUnitsRight = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int seekBarPrefValue = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int titleLayout = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int seek_bar_preference = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int beep = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int camera_swap_icon = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int camera_swap_icon_pressed = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int flashlight_turn_off_icon = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int flashlight_turn_off_icon_pressed = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int flashlight_turn_on_icon = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int flashlight_turn_on_icon_pressed = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int ic_btn_search = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int poweredby2x = 2131034120;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070009
			public const int app_name = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int hello = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int scanditsdk_barcode_decoding_in_progress = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int scanditsdk_barcode_presence_detected = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int scanditsdk_initial_scan_screen_state = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int scanditsdk_left_button_caption = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int scanditsdk_left_button_caption_when_keypad_visible = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int scanditsdk_right_button_caption = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int scanditsdk_right_button_caption_when_keypad_visible = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int scanditsdk_searchbar_placeholder = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int scanditsdk_title_message = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int version = 2131165194;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
